
title: Zi cu Soare
email: contact@zi-cu-soare.ro
description: Un blog pentru părinți și copii

baseurl: ""
url: "http://zi-cu-soare.ro"
twitter_username: zi_cu_soare
github_username:  zi-cu-soare
author: ana # Default author

defaults:
  -
    scope:
      type: posts
    values:
      layout: post
      author: ana

# Build settings
permalink: /:year/:month/:title
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: true

compress_html:
  blanklines: true

gems:
  - jekyll-feed
  - jekyll-sitemap
  - jemoji
exclude:
  - Gemfile
  - Gemfile.lock
